### PR TITLE
add basic Array/NativeArray implementation

### PR DESCRIPTION
**Pull request by mockey**
Here's a basic Array implementation with NativeArray as an abstract and NativeArrayI as an abstract for an indexed array. Not complete, just some code I had lying around from earlier experiments.
Note that `@:coreType NativeArray<T>` causes the compiler to hang. There seems to be something wrong with handling abstracts without underlying type (`@coreType`).

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Why do you need `@:coreType` on these abstracts?

**Comment by mockey** [comment]
Because NativeArray is `@:coreType` (native to the PHP target). Underlying `Dynamic` is not so good in this case, I think.

**Comment by RealyUniqueName** [comment]
Perhaps `NativeArray` should not have type parameters since it's always "dynamic" in php?

Otherwise can we do something like this?

``` haxe
private extern class PhpArray {}

abstract NativeArray<T> (PhpArray) {...}
```

**Comment by mockey** [comment]
> Perhaps NativeArray should not have type parameters since it's always "dynamic" in php?

Actually I wanted to avoid `dynamic`. My intention was to have typed native arrays whereever possible.

That's why I have a typed indexed array `NativeArrayI<T>` that can be casted to and from `Array<T>` and a typed associative array `NativeArrayA<T>`, where T can be a struct like `{foo: "bar", prop: 2}`, that can be casted to and from this struct. Anything else would be `NativeArray<Dynamic>` or an extra type `NativeArrayD` or something.
This is how I work with native arrays ATM, but maybe it's too complicated for the std lib (or maybe it doesn't make sense at all, I'm not so sure right now :-)

> Otherwise can we do something like this?
> private extern class PhpArray {}

Why? To avoid `@:coreType`?

**Comment by RealyUniqueName** [comment]
> Why? To avoid @:coreType?

In case we won't find the way to declare generic abstract without underlying type

**Comment by RealyUniqueName** [comment]
And i think there should not be implicit conversion between `NativeArray` and `NativeArrayI`, because `NativeArray` can contain data  incompatible with `NativeArrayI` behavior.

**Comment by mockey** [comment]
Hm, OK, `NativeArray` is just the underlying base type, so that I don't have to declare all functions twice for `NativeArrayI` and `NativeArrayA` but can `@:forward` them. It's never really used. But I agree that it's a bit strange that way and it's causing some additional casts, too.
How about having `NativeArray` without `T` as coreType then?

**Comment by mockey** [comment]
I have another idea:
Maybe we can avoid this whole wrapping business when we have an abstract `HxArray` which is nothing but a php array with an additional `__hx_id__` field, which is a unique id for the array instance, so we can do instance comparison based on this id:

``` haxe
[1,2,3] == [1,2,3];
a['__hx_id__'] == b['__hx_id__'];
```

Operator overloading of `==` is possible, isn't it?

Would a typedef, like:

``` haxe
#if php
typedef Array = HxArray;
#end
```

work?

Still it would be good to have a `@coreType abstract NativeArray`
http://haxe.org/manual/types-abstract-core-type.html says:
They are allowed to declare array access functions without expressions.
(I don't understand what that means exactly, though, have to try...)

**Comment by RealyUniqueName** [comment]
> Maybe we can avoid this whole wrapping business when we have an abstract HxArray which is nothing but a php array with an additional **hx_id** field, which is a unique id for the array instance, so we can do instance comparison based on this id

In this case we still need to convert to/from ordinary php array when interacting with external code, json still needs additonal handling. So it just complicates generator without any benefits :)

**Comment by benmerckx** [comment]
Avoiding the wrapping business would be nice :) I thought about it some more but, unless it can be tracked in the compiler, you can't really have the same equality check on native arrays. Your suggestion could work but would require all methods to check the hx_id field. Also any other native code can't use such array - they'd have to be converted again.

I don't feel like the equality check is that important. To me it feels like it could be a documented gotcha of the target if it means having added performance, native json encoding/decoding and easier interfacing. It might be more important to other people though, so I can't really judge. It seems like other targets have [other issues](https://github.com/HaxeFoundation/haxe/issues/4340) with it anyway, so it can't really be relied upon in cross-platform code.

In any case if the equality is important, you could create your wrapper by extending php's [`ArrayObject`](http://php.net/manual/en/class.arrayobject.php). It would have a few benefits when interfacing with native code.

``` php
<?php

$a = new ArrayObject([1,2,3]);
$b = new ArrayObject([1,2,3]);

var_dump($a === $b);
var_dump($a === $a);
```

**Comment by mockey** [comment]
> In this case we still need to convert to/from ordinary php array when interacting with external code, json still needs additonal handling. So it just complicates generator without any benefits :)

Hm, that's right, probably better to keep the unmodified array in a wrapper then. Was just an idea that hit me. Thanks for keeping me from trying it :-)

> I don't feel like the equality check is that important. To me it feels like it could be a documented gotcha of the target

I don't think so. Arrays being treated as instances (and passed by reference) is one of the basic rules of Haxe, I guess.

> It seems like other targets have other issues with it anyway

Well, `Int` vs. `Null<Int>` is something else than `Array` vs. `Array`, but sure, there are always issues.

> In any case if the equality is important, you could create your wrapper by extending php's ArrayObject.

ArrayObject used to have pretty terrible performance in old PHP versions but that's probably better now. It still seems quite weird to me but it might be worth trying if it performs better than our wrapper. It would be more interesting if it had functions like map or filter built in. These mean unwrapping the array, run array_map/filter and wrapping it again, no?

**Comment by RealyUniqueName** [comment]
I doubt `ArrayObject` can perform better than custom wrapper, which basically is just plain `StdClass` with two fields (native array and array length). 
We can implement `ArrayAccess`, `Countable` and `Iterable` if we want to pass Haxe array to external code without unwrapping.

**Comment by benmerckx** [comment]
Never mind ArrayObject, it doesn't seem that helpful after reading up on it :) I guess unwrapping/wrapping is probably the best way forward. The implementation here is simple enough. Is only `@:coreType` stopping this?

**Comment by mockey** [comment]
Oh, I quickly added `HxArray::wrap` to genphp7. I actually didn't want to commit this.
Maybe better do a new fork and a clean PR?

**Comment by RealyUniqueName** [comment]
That would be great. Also, please, add `[php7]` to commit messages if it's still possible

**Pull request closed without merging**
