### PR TITLE
Extern Array<T> class

### PR DESCRIPTION
**Pull request by benmerckx**
One of the things I'd like to see happen the most is an extern array. This PR is an example of how this could work.

Pros:
- Way better interoperability with existing code and native php libraries
- Provided objects and base values are also core types, json encoding/decoding can happen much faster
- No more NativeArray

Cons:
- No dynamic access, unless value is checked for is_array every time and method redirected (but there was no dynamic access for NativeArray anyway)

This implementation should mostly work. The only thing which will definitely fail is `new Array()`, I think that should be fixed in the compiler.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Need to figure out how to resolve situations like with passing array methods as closures:

``` haxe
var a = [1, 2, 3];
doStuff(a.pop);

//...

function doStuff(container:Void->Int) {
    //...
}
```

It's always an option to handle special cases in the compiler, but the more such cases moved to compiler the harder it becomes to maintain and add new features.

**Comment by benmerckx** [comment]
I did not even consider that at all. I've tried an abstract implementation to fix this. It should work more or less the same way, but methods can also be passed as closures. There's one downside: classes with `@:coreApi` which use Array will no longer unify with their core type (because Array is expected to be TInst, not TAbstract). I've removed the `@:coreApi` for now and also commented std code which expected TInst (most of it will be rewritten anyway).

**Comment by benmerckx** [comment]
``` haxe
public static function main() {
    var a = [1,2,3];
    a.pop();
    doStuff(a.pop);
}
```

Compiles to:

``` php
static public function main ()
{
    $a = [
            1,
            2,
            3,
    ];
    array_pop($a);
    $_e = $a;
    \Test::doStuff(function () {
            return array_pop($_e);
    });
}
```

**Comment by RealyUniqueName** [comment]
Unfortunately changing `Array` to abstract is impossible (at least before Haxe 4).

**Comment by RealyUniqueName** [comment]
After some thinking i've came to conclusion it's probably not so difficult to support array as an extern on the compiler level.
However it will require additional runtime checks when dealing with dynamic. But it's probably not a big deal since in Haxe you're supposed to keep usage Dynamic as low as possible. 
And we can help users to avoid Dynamic completely if expected [extern generator](https://github.com/RealyUniqueName/haxe/issues/20) will generate `Any` instead of `Dynamic`

**Comment by RealyUniqueName** [comment]
I've created an issue to keep all roadmap-related things in one place: https://github.com/RealyUniqueName/haxe/issues/32
Please post further comments into that issue.

**Pull request closed without merging**
